CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Addresses" (
    "Id" uuid NOT NULL,
    "Street" text NOT NULL,
    "HouseNumber" text NOT NULL,
    "FlatNumber" integer NOT NULL,
    "PostalCode" text NOT NULL,
    "City" text NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "BasicHealthInfos" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Age" integer NOT NULL,
    "Size" integer NOT NULL,
    "IsNeutered" boolean NOT NULL,
    CONSTRAINT "PK_BasicHealthInfos" PRIMARY KEY ("Id")
);

CREATE TABLE "CalendarActivities" (
    "Id" uuid NOT NULL,
    CONSTRAINT "PK_CalendarActivities" PRIMARY KEY ("Id")
);

CREATE TABLE "BasicInformations" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Surname" text NOT NULL,
    "Phone" text NOT NULL,
    "AddressId" uuid NULL,
    CONSTRAINT "PK_BasicInformations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BasicInformations_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Diseases" (
    "Id" uuid NOT NULL,
    "NameOfdisease" text NOT NULL,
    "IllnessStart" timestamp with time zone NOT NULL,
    "IllnessEnd" timestamp with time zone NOT NULL,
    "BasicHealthInfoId" uuid NULL,
    CONSTRAINT "PK_Diseases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Diseases_BasicHealthInfos_BasicHealthInfoId" FOREIGN KEY ("BasicHealthInfoId") REFERENCES "BasicHealthInfos" ("Id")
);

CREATE TABLE "Vaccinations" (
    "Id" uuid NOT NULL,
    "VaccinationName" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "BasicHealthInfoId" uuid NULL,
    CONSTRAINT "PK_Vaccinations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vaccinations_BasicHealthInfos_BasicHealthInfoId" FOREIGN KEY ("BasicHealthInfoId") REFERENCES "BasicHealthInfos" ("Id")
);

CREATE TABLE "Activities" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "StartActivityDate" timestamp with time zone NOT NULL,
    "EndActivityDate" timestamp with time zone NOT NULL,
    "CalendarActivityId" uuid NOT NULL,
    CONSTRAINT "PK_Activities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Activities_CalendarActivities_CalendarActivityId" FOREIGN KEY ("CalendarActivityId") REFERENCES "CalendarActivities" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Shelters" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "CalendarId" uuid NOT NULL,
    "AddressId" uuid NOT NULL,
    "PhoneNumber" text NOT NULL,
    "ShelterDescription" text NOT NULL,
    "BankNumber" text NOT NULL,
    "Image" bytea NOT NULL,
    CONSTRAINT "PK_Shelters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shelters_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Shelters_CalendarActivities_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "CalendarActivities" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "RefreshToken" text NULL,
    "RefreshTokenExpiration" timestamp with time zone NULL,
    "BasicInformationId" uuid NOT NULL,
    "UserCalendarId" uuid NOT NULL,
    "ShelterId" uuid NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_BasicInformations_BasicInformationId" FOREIGN KEY ("BasicInformationId") REFERENCES "BasicInformations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUsers_CalendarActivities_UserCalendarId" FOREIGN KEY ("UserCalendarId") REFERENCES "CalendarActivities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUsers_Shelters_ShelterId" FOREIGN KEY ("ShelterId") REFERENCES "Shelters" ("Id")
);

CREATE TABLE "Adoptions" (
    "Id" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "IsPreAdoptionPoll" boolean NOT NULL,
    "PreadoptionPoll" text NOT NULL,
    "CalendarId" uuid NULL,
    "IsMeetings" boolean NOT NULL,
    "IsContractAdoption" boolean NOT NULL,
    "ContractAdoption" text NULL,
    "DateOfAdoption" timestamp with time zone NULL,
    "ShelterId" uuid NULL,
    CONSTRAINT "PK_Adoptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Adoptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Adoptions_CalendarActivities_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "CalendarActivities" ("Id"),
    CONSTRAINT "FK_Adoptions_Shelters_ShelterId" FOREIGN KEY ("ShelterId") REFERENCES "Shelters" ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Title" integer NOT NULL,
    "UserId" uuid NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Roles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "TempHouses" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AddressId" uuid NOT NULL,
    "IsPreTempHousePoll" boolean NOT NULL,
    "TempHousePoll" text NOT NULL,
    "CalendarId" uuid NULL,
    "ActivityId" uuid NULL,
    "IsMeetings" boolean NOT NULL,
    "StartOfTemporaryHouseDate" timestamp with time zone NOT NULL,
    "ShelterId" uuid NULL,
    CONSTRAINT "PK_TempHouses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TempHouses_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TempHouses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TempHouses_CalendarActivities_ActivityId" FOREIGN KEY ("ActivityId") REFERENCES "CalendarActivities" ("Id"),
    CONSTRAINT "FK_TempHouses_Shelters_ShelterId" FOREIGN KEY ("ShelterId") REFERENCES "Shelters" ("Id")
);

CREATE TABLE "Pets" (
    "Id" uuid NOT NULL,
    "Gender" integer NOT NULL,
    "Type" integer NOT NULL,
    "BasicHealthInfoId" uuid NOT NULL,
    "Description" text NOT NULL,
    "CalendarId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "AvaibleForAdoption" boolean NOT NULL,
    "Image" bytea NOT NULL,
    "ShelterId" uuid NOT NULL,
    "TempHouseId" uuid NULL,
    CONSTRAINT "PK_Pets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pets_BasicHealthInfos_BasicHealthInfoId" FOREIGN KEY ("BasicHealthInfoId") REFERENCES "BasicHealthInfos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Pets_CalendarActivities_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "CalendarActivities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Pets_Shelters_ShelterId" FOREIGN KEY ("ShelterId") REFERENCES "Shelters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Pets_TempHouses_TempHouseId" FOREIGN KEY ("TempHouseId") REFERENCES "TempHouses" ("Id")
);

CREATE TABLE "UserPet" (
    "UserId" uuid NOT NULL,
    "PetId" uuid NOT NULL,
    CONSTRAINT "PK_UserPet" PRIMARY KEY ("PetId", "UserId"),
    CONSTRAINT "FK_UserPet_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPet_Pets_PetId" FOREIGN KEY ("PetId") REFERENCES "Pets" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Activities_CalendarActivityId" ON "Activities" ("CalendarActivityId");

CREATE UNIQUE INDEX "IX_Adoptions_CalendarId" ON "Adoptions" ("CalendarId");

CREATE INDEX "IX_Adoptions_ShelterId" ON "Adoptions" ("ShelterId");

CREATE INDEX "IX_Adoptions_UserId" ON "Adoptions" ("UserId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_BasicInformationId" ON "AspNetUsers" ("BasicInformationId");

CREATE INDEX "IX_AspNetUsers_ShelterId" ON "AspNetUsers" ("ShelterId");

CREATE UNIQUE INDEX "IX_AspNetUsers_UserCalendarId" ON "AspNetUsers" ("UserCalendarId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_BasicInformations_AddressId" ON "BasicInformations" ("AddressId");

CREATE INDEX "IX_Diseases_BasicHealthInfoId" ON "Diseases" ("BasicHealthInfoId");

CREATE UNIQUE INDEX "IX_Pets_BasicHealthInfoId" ON "Pets" ("BasicHealthInfoId");

CREATE UNIQUE INDEX "IX_Pets_CalendarId" ON "Pets" ("CalendarId");

CREATE INDEX "IX_Pets_ShelterId" ON "Pets" ("ShelterId");

CREATE INDEX "IX_Pets_TempHouseId" ON "Pets" ("TempHouseId");

CREATE INDEX "IX_Roles_UserId" ON "Roles" ("UserId");

CREATE INDEX "IX_Shelters_AddressId" ON "Shelters" ("AddressId");

CREATE UNIQUE INDEX "IX_Shelters_CalendarId" ON "Shelters" ("CalendarId");

CREATE INDEX "IX_TempHouses_ActivityId" ON "TempHouses" ("ActivityId");

CREATE INDEX "IX_TempHouses_AddressId" ON "TempHouses" ("AddressId");

CREATE INDEX "IX_TempHouses_ShelterId" ON "TempHouses" ("ShelterId");

CREATE UNIQUE INDEX "IX_TempHouses_UserId" ON "TempHouses" ("UserId");

CREATE INDEX "IX_UserPet_UserId" ON "UserPet" ("UserId");

CREATE INDEX "IX_Vaccinations_BasicHealthInfoId" ON "Vaccinations" ("BasicHealthInfoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231119213509_initialMigration', '7.0.11');

COMMIT;

